feat: Update 03-rpiraces-plain.md
ps-developers-sandbox/caption-this-20230918 pull request #20
Opened 2023-09-18 09:57 UTC by rpiraces-plain

2023-09-18 10:00 UTC, marktaylor72 reviewed
LGTM

2023-09-18 10:00 UTC, bernat-nosas approved these changes

2023-09-18 15:11 UTC, piraces requested changes

2023-09-18 15:11 UTC, piraces commented on _slides/03-rpiraces-plain.md
> +**Hello world!** RPiraces here! 🦁
I think this will be better in two lines...

```suggestion
**Hello world!**
RPiraces here! 🦁
```

2023-09-19 07:27 UTC, piraces requested changes
Please review...

2023-09-19 07:27 UTC, piraces commented on _slides/03-rpiraces-plain.md
>  ![constructocat](https://octodex.github.com/images/constructocat2.jpg)
```suggestion
![constructocat](https://octodex.github.com/images/Sentrytocat_octodex.jpg)
```

2023-09-19 07:28 UTC, piraces approved these changes
LGTM!

2023-09-19 07:29 UTC, merged

2023-09-19 07:29 UTC, emoralesbe reviewed
Please review (@emoralesbe )
https://octodex.github.com/images/luchadortocat.png